insert into public.pricing_plans (id, name, slug, price, currency, interval, features, is_popular, is_active)
values
  ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1', 'Starter', 'starter', 0, 'USD', 'one_time', array['Course catalog access', 'Free lessons', 'Certificate verification'], false, true),
  ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2', 'Academy Pro', 'academy-pro', 149, 'USD', 'one_time', array['All courses', 'Practice assignments', 'Instructor reviews', 'Certificates'], true, true),
  ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3', 'Team Training', 'team-training', 499, 'USD', 'month', array['Team enrollments', 'Admin analytics', 'Instructor dashboards', 'Priority support'], false, true)
on conflict (slug) do update
set name = excluded.name,
    price = excluded.price,
    currency = excluded.currency,
    interval = excluded.interval,
    features = excluded.features,
    is_popular = excluded.is_popular,
    is_active = excluded.is_active;

insert into public.courses (
  id,
  slug,
  title,
  subtitle,
  description,
  category,
  image_url,
  difficulty,
  duration_hours,
  instructor_name,
  instructor_bio,
  instructor_avatar_url,
  enrollment_count,
  certificate_available,
  learning_outcomes,
  prerequisites,
  common_mistakes,
  quiz_threshold,
  published,
  last_updated
)
values
  (
    '11111111-1111-4111-8111-111111111111',
    'dispatch-fundamentals',
    'Dispatch Fundamentals',
    'Master the basics of trucking dispatch operations',
    'Learn foundational dispatch workflows, freight stakeholders, tools, broker communication, and first-load operations.',
    'Dispatch',
    '/courses/dispatch-fundamentals.png',
    'beginner',
    12,
    'Alisher Karimov',
    'Dispatch operations trainer focused on load planning and broker communication.',
    '/instructor-2.png',
    1243,
    true,
    array['Understand freight dispatcher responsibilities', 'Navigate freight workflows', 'Communicate with drivers and brokers', 'Track a load from pickup to delivery'],
    array['No prior dispatch experience required'],
    array['Failing to confirm load details in writing', 'Confusing broker and carrier roles'],
    70,
    true,
    '2026-06-04'
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'broker-communication',
    'Broker Communication',
    'Build strong broker relationships through professional communication',
    'Practice professional email writing, rate negotiation, objection handling, and relationship management with freight brokers.',
    'Business',
    '/courses/broker-communication.png',
    'intermediate',
    8,
    'Nodira Azimova',
    'Broker communication trainer focused on negotiation and carrier-broker workflows.',
    '/instructor-3.png',
    876,
    true,
    array['Write professional broker emails', 'Negotiate rates with evidence', 'Handle difficult broker conversations'],
    array['Basic dispatch terminology'],
    array['Quoting without lane context', 'Using unclear confirmation language'],
    75,
    true,
    '2026-06-04'
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'load-board-mastery',
    'Load Board Mastery',
    'Read load boards, evaluate lanes, and avoid bad freight',
    'Learn how to evaluate posts, calculate RPM, identify broker risk, and make safer booking decisions.',
    'Operations',
    '/courses/load-board-mastery.png',
    'intermediate',
    10,
    'Jasur Tashmatov',
    'Load board specialist focused on practical lane evaluation and risk signals.',
    '/instructor-1.png',
    642,
    true,
    array['Read load board posts accurately', 'Calculate RPM and deadhead impact', 'Identify double-brokering red flags'],
    array['Basic broker communication'],
    array['Ignoring deadhead miles', 'Accepting unusually high rates without broker checks'],
    75,
    true,
    '2026-06-04'
  ),
  (
    '44444444-4444-4444-8444-444444444444',
    'amazon-style-freight-training',
    'Amazon-Style Freight Training',
    'Relay-style training for appointment-based loads',
    'Independent training for Amazon-style freight scenarios with strict appointments, trailer checks, facility workflows, delay communication, and route timing discipline.',
    'Operations',
    '/courses/amazon-style-freight-training.png',
    'intermediate',
    7,
    'Alisher Karimov',
    'Dispatch operations trainer focused on load planning, broker communication, and practical workflow habits.',
    '/instructor-2.png',
    318,
    true,
    array['Explain Amazon-style freight and Relay-style training scenarios', 'Manage strict pickup and delivery appointment windows', 'Verify trailer requirements before dispatch', 'Communicate detention and delay risk clearly', 'Evaluate rate, route, timing, and service risk'],
    array['Dispatch Fundamentals', 'Load Board Training recommended'],
    array['Treating appointment-based loads like flexible freight', 'Missing trailer requirement checks', 'Waiting too long to communicate a delay'],
    75,
    true,
    '2026-06-05'
  ),
  (
    '55555555-5555-4555-8555-555555555555',
    'usps-postal-freight-training',
    'USPS / Postal Freight Training',
    'USPS-related freight training for postal-style freight operations',
    'Independent training for postal-style freight scenarios with time-sensitive lanes, drop-and-hook basics, documentation requirements, trailer cleanliness, seal checks, and on-time performance habits.',
    'Operations',
    '/courses/usps-postal-freight-training.png',
    'intermediate',
    6,
    'Timur Rakhimov',
    'Compliance and fleet safety trainer focused on HOS, documentation habits, and safety-aware dispatch decisions.',
    '/instructor-2.png',
    284,
    true,
    array['Explain postal-style freight and timing expectations', 'Plan time-sensitive lanes with realistic buffers', 'Manage drop-and-hook trailer status', 'Verify documentation and seal checks', 'Use a dispatcher checklist for USPS-related freight training scenarios'],
    array['Dispatch Fundamentals', 'HOS / ELD Basics recommended'],
    array['Underestimating postal-style freight timing', 'Skipping seal verification', 'Failing to confirm drop-and-hook trailer numbers'],
    75,
    true,
    '2026-06-05'
  )
on conflict (slug) do update
set title = excluded.title,
    subtitle = excluded.subtitle,
    description = excluded.description,
    category = excluded.category,
    image_url = excluded.image_url,
    difficulty = excluded.difficulty,
    duration_hours = excluded.duration_hours,
    instructor_name = excluded.instructor_name,
    instructor_bio = excluded.instructor_bio,
    instructor_avatar_url = excluded.instructor_avatar_url,
    enrollment_count = excluded.enrollment_count,
    certificate_available = excluded.certificate_available,
    learning_outcomes = excluded.learning_outcomes,
    prerequisites = excluded.prerequisites,
    common_mistakes = excluded.common_mistakes,
    quiz_threshold = excluded.quiz_threshold,
    published = excluded.published,
    last_updated = excluded.last_updated;

insert into public.cohorts (id, name, slug, course_id, starts_at, ends_at, capacity, status)
values
  ('dddddddd-dddd-4ddd-8ddd-dddddddddd01', 'Summer 2026', 'summer-2026', '11111111-1111-4111-8111-111111111111', '2026-06-15', '2026-08-28', 35, 'planned'),
  ('dddddddd-dddd-4ddd-8ddd-dddddddddd02', 'Fall 2026', 'fall-2026', '11111111-1111-4111-8111-111111111111', '2026-09-08', '2026-11-20', 35, 'planned'),
  ('dddddddd-dddd-4ddd-8ddd-dddddddddd03', 'Dispatcher Elite', 'dispatcher-elite', '22222222-2222-4222-8222-222222222222', '2026-07-06', '2026-10-02', 20, 'planned'),
  ('dddddddd-dddd-4ddd-8ddd-dddddddddd04', 'Amazon Operations', 'amazon-operations', '44444444-4444-4444-8444-444444444444', '2026-07-20', '2026-09-18', 25, 'planned')
on conflict (slug) do update
set name = excluded.name,
    course_id = excluded.course_id,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    capacity = excluded.capacity,
    status = excluded.status;

insert into public.lessons (
  id,
  course_id,
  order_index,
  title,
  description,
  content,
  duration_min,
  is_free,
  is_required,
  checklist,
  resources
)
values
  (
    '11111111-1111-4111-8111-000000000001',
    '11111111-1111-4111-8111-111111111111',
    1,
    'Introduction to Freight Dispatching',
    'Overview of what a dispatcher does and why the role matters.',
    'Freight dispatching is the coordination hub between shippers, brokers, carriers, and drivers. This lesson introduces core responsibilities and daily dispatch desk habits.',
    45,
    true,
    true,
    array['Define the role of a freight dispatcher', 'List key freight stakeholders', 'Describe a typical dispatcher workday'],
    '[{"title":"FMCSA Beginner Guide","url":"https://www.fmcsa.dot.gov","type":"link"}]'::jsonb
  ),
  (
    '11111111-1111-4111-8111-000000000002',
    '11111111-1111-4111-8111-111111111111',
    2,
    'Dispatcher Tools and Software',
    'Set up the dispatch workstation and understand common tools.',
    'Modern dispatchers use TMS platforms, load boards, ELD portals, email, and phone systems. This lesson explains what each tool is used for.',
    55,
    false,
    true,
    array['List common TMS tools', 'Explain how load boards are used', 'Describe how ELD data helps dispatchers'],
    '[{"title":"Load Board Platform Guide","url":"#","type":"document"}]'::jsonb
  ),
  (
    '11111111-1111-4111-8111-000000000003',
    '11111111-1111-4111-8111-111111111111',
    3,
    'Handling Your First Load',
    'Practice dispatching a load from search to delivery.',
    'This capstone lesson walks through finding a load, negotiating, assigning a driver, tracking status, and closing paperwork.',
    65,
    false,
    true,
    array['Find a simulated load', 'Negotiate a rate', 'Track the load through delivery'],
    '[{"title":"Load Dispatch Checklist","url":"#","type":"pdf"}]'::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000001',
    '22222222-2222-4222-8222-222222222222',
    1,
    'Professional Broker Email',
    'Write concise broker emails that get clear answers.',
    'Learn subject lines, rate language, confirmations, and follow-up structure for broker communication.',
    40,
    true,
    true,
    array['Write a clear subject line', 'Confirm load details in writing', 'Use a professional tone'],
    '[{"title":"Broker Email Template","url":"#","type":"template"}]'::jsonb
  ),
  (
    '22222222-2222-4222-8222-000000000002',
    '22222222-2222-4222-8222-222222222222',
    2,
    'Rate Negotiation Basics',
    'Use lane evidence and market context to negotiate.',
    'This lesson covers rate framing, silence, counteroffers, and how to justify a fair rate with RPM and lane context.',
    50,
    false,
    true,
    array['Calculate a target RPM', 'Write a counteroffer', 'Document the accepted rate'],
    '[]'::jsonb
  ),
  (
    '33333333-3333-4333-8333-000000000001',
    '33333333-3333-4333-8333-333333333333',
    1,
    'Reading Load Board Posts',
    'Understand load board fields, rate quality, and risk signals.',
    'Learn to scan origin, destination, equipment, pickup window, weight, broker score, rate, and notes before calling.',
    45,
    true,
    true,
    array['Identify required fields', 'Calculate rate per mile', 'Spot missing details'],
    '[{"title":"Load Board Field Checklist","url":"#","type":"checklist"}]'::jsonb
  ),
  (
    '33333333-3333-4333-8333-000000000002',
    '33333333-3333-4333-8333-333333333333',
    2,
    'Load Board Risk Signals',
    'Identify risky posts, broker gaps, and rate traps before booking.',
    'This lesson teaches dispatchers to review broker history, pickup details, equipment requirements, appointment timing, rate quality, and double-brokering red flags before committing a truck.',
    50,
    false,
    true,
    array['Check broker history before booking', 'Identify vague or risky load details', 'Explain when to verify or reject a posted load'],
    '[{"title":"Load Board Risk Review Worksheet","url":"#","type":"worksheet"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000001',
    '44444444-4444-4444-8444-444444444444',
    1,
    'What Amazon Relay-style Loads Are',
    'Understand the structure of Amazon-style freight without endorsement claims.',
    'Amazon-style freight often runs through appointment-based facilities with tight pickup and delivery expectations. This Relay-style training uses realistic dispatch scenarios and neutral freight examples.',
    35,
    true,
    true,
    array['Define Amazon-style freight in neutral operational terms', 'Describe why appointment discipline matters', 'Identify dispatcher responsibilities before booking'],
    '[{"title":"Appointment Freight Overview","url":"#","type":"document"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000002',
    '44444444-4444-4444-8444-444444444444',
    2,
    'Appointment Windows and Strict Timing',
    'Plan pickup and delivery timing around narrow facility windows.',
    'Appointment-based freight requires precise time planning across pickup windows, delivery windows, driver hours, traffic buffers, fuel stops, and facility staging rules.',
    45,
    false,
    true,
    array['Confirm appointment times in writing', 'Build a route timeline with staging buffers', 'Check driver HOS against both appointment windows'],
    '[{"title":"Appointment Timing Planner","url":"#","type":"template"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000003',
    '44444444-4444-4444-8444-444444444444',
    3,
    'Trailer Requirements',
    'Verify trailer type, condition, and readiness before dispatch.',
    'Amazon-style freight may require specific trailer type, clean condition, working lights, damage-free panels, and proper registration. Dispatchers should verify requirements before assigning the truck.',
    40,
    false,
    true,
    array['Confirm trailer type and door requirements', 'Ask for trailer number and condition', 'Document requirement confirmations before pickup'],
    '[{"title":"Trailer Readiness Checklist","url":"#","type":"checklist"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000004',
    '44444444-4444-4444-8444-444444444444',
    4,
    'Check-in / Check-out Basics',
    'Coach drivers through facility arrival, gate, and departure steps.',
    'Check-in and check-out workflows can include guard shack arrival, appointment ID, trailer number, dock assignment, seal recording, paperwork review, and departure confirmation.',
    40,
    false,
    true,
    array['Send appointment and facility details', 'Confirm arrival and gate check-in status', 'Capture check-out time and paperwork status'],
    '[{"title":"Facility Check-in Script","url":"#","type":"template"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000005',
    '44444444-4444-4444-8444-444444444444',
    5,
    'Detention and Delay Communication',
    'Escalate late arrivals, loading delays, and detention risk professionally.',
    'Delay communication must be fast, factual, and documented. Dispatchers should report current location, cause, updated ETA, appointment impact, and recovery options.',
    45,
    false,
    true,
    array['Notify stakeholders before an appointment is missed', 'Send factual ETA updates', 'Track arrival, dock, loaded, and departure times'],
    '[{"title":"Delay Update Template","url":"#","type":"template"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000006',
    '44444444-4444-4444-8444-444444444444',
    6,
    'Common Mistakes with Amazon-style Freight',
    'Avoid errors that cause rejections, missed appointments, and disputes.',
    'Common mistakes include booking before checking HOS, ignoring traffic buffers, using an unqualified trailer, missing arrival instructions, failing to document detention, and sending vague delay messages.',
    40,
    false,
    true,
    array['Identify common rejection triggers', 'Build a pre-dispatch verification habit', 'Use documentation to reduce disputes'],
    '[{"title":"Common Mistakes Review Sheet","url":"#","type":"document"}]'::jsonb
  ),
  (
    '44444444-4444-4444-8444-000000000007',
    '44444444-4444-4444-8444-444444444444',
    7,
    'Dispatcher Checklist for Appointment-based Loads',
    'Use a repeatable checklist before booking and dispatching strict appointment freight.',
    'A strong appointment-based load checklist covers rate, route, facility window, HOS, trailer requirements, driver instructions, contact details, delay escalation, detention records, and closeout paperwork.',
    50,
    false,
    true,
    array['Complete a pre-booking rate and route check', 'Confirm appointment and trailer details', 'Close the load with times, paperwork, and notes'],
    '[{"title":"Appointment-based Load Checklist","url":"#","type":"checklist"},{"title":"Rate and Route Evaluation Worksheet","url":"#","type":"template"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000001',
    '55555555-5555-4555-8555-555555555555',
    1,
    'What Postal-style Freight Is',
    'Understand the operating expectations behind postal-style freight.',
    'Postal-style freight is time-sensitive freight that often follows fixed lane schedules, strict pickup expectations, and clean documentation habits.',
    35,
    true,
    true,
    array['Define postal-style freight in operational terms', 'Explain why fixed schedules affect dispatch decisions', 'Use USPS-related freight training language safely'],
    '[{"title":"Postal-style Freight Overview","url":"#","type":"document"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000002',
    '55555555-5555-4555-8555-555555555555',
    2,
    'Time-sensitive Lane Management',
    'Plan lanes where late pickup or delivery can create service failures.',
    'Time-sensitive lane management starts before booking. Dispatchers verify mileage, traffic patterns, driver HOS, facility hours, weather, and contingency options.',
    45,
    false,
    true,
    array['Build a lane timeline with conservative buffers', 'Check HOS against commitments', 'Escalate risk before appointment failure'],
    '[{"title":"Route Timing Exercise","url":"#","type":"template"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000003',
    '55555555-5555-4555-8555-555555555555',
    3,
    'Drop-and-hook Basics',
    'Track dropped, hooked, empty, and loaded trailer status clearly.',
    'Drop-and-hook freight can be efficient when trailer status is clear. Dispatchers confirm trailer number, loaded or empty status, seal, location, release time, and departure steps.',
    40,
    false,
    true,
    array['Confirm dropped and hooked trailer numbers', 'Record loaded, empty, and released statuses', 'Update stakeholders when a trailer is not ready'],
    '[{"title":"Drop-and-hook Status Log","url":"#","type":"template"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000004',
    '55555555-5555-4555-8555-555555555555',
    4,
    'Documentation Requirements',
    'Keep paperwork complete, legible, and matched to the load.',
    'Documentation for postal-style freight should verify load identifiers, trailer numbers, seal numbers, pickup and delivery times, signatures when required, and customer-specific paperwork instructions.',
    40,
    false,
    true,
    array['Verify load ID and trailer number', 'Confirm required timestamps', 'Store documents with the correct load record'],
    '[{"title":"Postal-style Document Checklist","url":"#","type":"checklist"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000005',
    '55555555-5555-4555-8555-555555555555',
    5,
    'Trailer Cleanliness and Seal Checks',
    'Prevent rejection and claim risk with clean trailer and seal discipline.',
    'Trailer cleanliness and seal checks protect service and cargo integrity. Dispatchers remind drivers to inspect the trailer, confirm seal placement, record seal numbers, and escalate mismatches.',
    40,
    false,
    true,
    array['Confirm trailer is clean and dry', 'Record seal number before departure', 'Escalate seal mismatches immediately'],
    '[{"title":"Seal and Cleanliness Checklist","url":"#","type":"checklist"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000006',
    '55555555-5555-4555-8555-555555555555',
    6,
    'On-time Performance Importance',
    'Understand how timing discipline affects service quality.',
    'On-time performance is a core measure for time-sensitive freight. Dispatchers protect it through planning, realistic ETAs, driver check calls, proactive delay notices, and complete timestamps.',
    40,
    false,
    true,
    array['Track pickup and delivery milestones', 'Use proactive ETA updates', 'Review service failures for prevention steps'],
    '[{"title":"On-time Performance Review","url":"#","type":"document"}]'::jsonb
  ),
  (
    '55555555-5555-4555-8555-000000000007',
    '55555555-5555-4555-8555-555555555555',
    7,
    'Dispatcher Checklist for Postal Freight',
    'Apply a complete checklist for postal-style freight dispatch.',
    'The postal freight checklist combines lane timing, HOS, facility instructions, trailer status, seal checks, documentation, delay escalation, and closeout review.',
    45,
    false,
    true,
    array['Complete lane and HOS timing checks', 'Verify drop-and-hook trailer details', 'Record seal and document status', 'Close the load with required timestamps'],
    '[{"title":"Postal Freight Dispatcher Checklist","url":"#","type":"checklist"},{"title":"Route Timing Worksheet","url":"#","type":"template"}]'::jsonb
  )
on conflict (course_id, order_index) do update
set title = excluded.title,
    description = excluded.description,
    content = excluded.content,
    duration_min = excluded.duration_min,
    is_free = excluded.is_free,
    is_required = excluded.is_required,
    checklist = excluded.checklist,
    resources = excluded.resources;

insert into public.quizzes (id, course_id, lesson_id, title, questions, passing_score, published)
values
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1',
    '11111111-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-000000000003',
    'Dispatch Fundamentals Check',
    '[
      {"id":"q1","question":"Who confirms load details with the broker in writing?","options":["Dispatcher","Receiver","Fuel desk"],"correctIndex":0,"explanation":"The dispatcher should confirm load details and keep written records."},
      {"id":"q2","question":"What does RPM mean?","options":["Route planning manual","Revenue per mile","Rate pickup memo"],"correctIndex":1,"explanation":"RPM is total rate divided by total miles."}
    ]'::jsonb,
    70,
    true
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2',
    '22222222-2222-4222-8222-222222222222',
    '22222222-2222-4222-8222-000000000002',
    'Broker Communication Check',
    '[
      {"id":"q1","question":"What should a rate counteroffer include?","options":["A clear rate and reason","Only emojis","No lane details"],"correctIndex":0,"explanation":"A strong counteroffer states the rate and the business reason."},
      {"id":"q2","question":"Why confirm details by email?","options":["It slows the broker down","It creates a record","It replaces the rate confirmation"],"correctIndex":1,"explanation":"Written confirmation protects both sides before paperwork arrives."}
    ]'::jsonb,
    75,
    true
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3',
    '33333333-3333-4333-8333-333333333333',
    '33333333-3333-4333-8333-000000000002',
    'Load Board Mastery Check',
    '[
      {"id":"q1","question":"What should a dispatcher verify before booking a suspiciously high-paying load?","options":["Broker history, pickup details, equipment requirements, timing, and rate logic","Only the posted rate","Only the destination city"],"correctIndex":0,"explanation":"High pay with vague details should trigger broker, lane, equipment, and timing checks."},
      {"id":"q2","question":"What is a common load board red flag?","options":["Clear appointment details","Missing pickup information from a new broker account","Complete rate confirmation"],"correctIndex":1,"explanation":"Vague details from a new or unverified broker account can indicate higher booking risk."}
    ]'::jsonb,
    75,
    true
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb4',
    '44444444-4444-4444-8444-444444444444',
    '44444444-4444-4444-8444-000000000007',
    'Amazon-Style Freight Training Check',
    '[
      {"id":"q1","question":"What should be verified before accepting strict appointment freight?","options":["Only the posted rate","Appointment windows, HOS, route time, trailer requirements, and facility instructions","Only the delivery city"],"correctIndex":1,"explanation":"Appointment freight requires complete timing, equipment, and instruction checks."},
      {"id":"q2","question":"When should a likely appointment delay be communicated?","options":["As soon as the delay risk is known","After delivery","Never"],"correctIndex":0,"explanation":"Delay communication should be early, factual, and documented."}
    ]'::jsonb,
    75,
    true
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb5',
    '55555555-5555-4555-8555-555555555555',
    '55555555-5555-4555-8555-000000000007',
    'USPS / Postal Freight Training Check',
    '[
      {"id":"q1","question":"What is postal-style freight usually most sensitive to?","options":["Time, documentation, trailer status, and service reliability","Decorative trailer graphics","Invoice date only"],"correctIndex":0,"explanation":"Postal-style freight scenarios require strong timing, documentation, trailer, and service habits."},
      {"id":"q2","question":"What should happen when a seal number does not match paperwork?","options":["Ignore it","Escalate immediately and document the mismatch","Wait until invoicing"],"correctIndex":1,"explanation":"Seal mismatches should be escalated before departure or as soon as discovered."}
    ]'::jsonb,
    75,
    true
  )
on conflict (id) do update
set title = excluded.title,
    questions = excluded.questions,
    passing_score = excluded.passing_score,
    published = excluded.published;

insert into public.assignments (
  id,
  course_id,
  lesson_id,
  title,
  description,
  instructions,
  scenario,
  rubric,
  type,
  difficulty,
  published
)
values
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc1',
    '11111111-1111-4111-8111-111111111111',
    '11111111-1111-4111-8111-000000000003',
    'Dispatch Your First Load',
    'Submit a step-by-step dispatch plan for a simulated load.',
    'Explain how you would confirm pickup, assign a driver, track delivery, and close paperwork.',
    'A broker offers a dry van load from Chicago, IL to Atlanta, GA with next-day pickup. Build a dispatch plan.',
    '[{"criterion":"Workflow completeness","weight":40,"description":"Covers pickup, tracking, delivery, and paperwork."},{"criterion":"Communication quality","weight":30,"description":"Uses professional broker and driver language."},{"criterion":"Risk checks","weight":30,"description":"Mentions broker score, rate, and appointment confirmation."}]'::jsonb,
    'scenario',
    'beginner',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc2',
    '22222222-2222-4222-8222-222222222222',
    '22222222-2222-4222-8222-000000000002',
    'Broker Rate Counter Email',
    'Write a professional counteroffer email.',
    'Draft a concise broker email that counters the offered rate and asks for written confirmation.',
    'The broker offers $1,900 on a 780-mile lane. Your target is $2,250. Write the email.',
    '[{"criterion":"Clarity","weight":35,"description":"States the counteroffer clearly."},{"criterion":"Professional tone","weight":35,"description":"Keeps the broker relationship positive."},{"criterion":"Business reasoning","weight":30,"description":"Uses lane or RPM context."}]'::jsonb,
    'email',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc3',
    '33333333-3333-4333-8333-333333333333',
    '33333333-3333-4333-8333-000000000001',
    'Load Board Risk Review',
    'Review a load board post and identify risk signals.',
    'List the fields you would verify before booking and explain any red flags.',
    'A post shows high pay, vague pickup details, and a new broker account with limited history.',
    '[{"criterion":"Field review","weight":30,"description":"Checks required load board details."},{"criterion":"Risk detection","weight":40,"description":"Identifies likely red flags."},{"criterion":"Decision quality","weight":30,"description":"Explains book, reject, or verify decision."}]'::jsonb,
    'review',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc4',
    '44444444-4444-4444-8444-444444444444',
    '44444444-4444-4444-8444-000000000005',
    'Appointment Delay Scenario',
    'Handle a late-arrival risk on an Amazon-style freight appointment.',
    'Create an action plan with driver instructions, stakeholder notification, update cadence, documentation, and recovery steps.',
    'A driver is 55 miles from pickup for an Amazon-style freight load with a 2:00 PM appointment. A crash has slowed the route and the new ETA is 2:35 PM.',
    '[{"criterion":"Speed of escalation","weight":30,"description":"Notifies stakeholders before the appointment is missed."},{"criterion":"Driver instructions","weight":25,"description":"Instructions are safe and specific."},{"criterion":"Documentation","weight":20,"description":"Captures ETA, cause, location, timestamps, and facility response."},{"criterion":"Recovery options","weight":25,"description":"Includes practical recovery or reschedule steps."}]'::jsonb,
    'scenario',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc5',
    '44444444-4444-4444-8444-444444444444',
    '44444444-4444-4444-8444-000000000005',
    'Broker or Customer Email Response',
    'Write a delay update for a strict appointment-based load.',
    'Draft an email with current location, ETA, reason for delay, recovery request, next update time, and professional tone.',
    'A broker or customer contact asks why the truck has not checked in for an Amazon-style freight pickup. The driver is delayed by traffic and ETA is 35 minutes after the appointment.',
    '[{"criterion":"Factual clarity","weight":30,"description":"Gives location, ETA, reason, and appointment impact."},{"criterion":"Professional tone","weight":25,"description":"Keeps the message calm and direct."},{"criterion":"Recovery request","weight":25,"description":"Asks for a clear next step."},{"criterion":"Update cadence","weight":20,"description":"States when the next update will be sent."}]'::jsonb,
    'email',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc6',
    '44444444-4444-4444-8444-444444444444',
    '44444444-4444-4444-8444-000000000007',
    'Rate and Route Evaluation Worksheet',
    'Evaluate whether an appointment-based load is worth booking.',
    'Calculate all-in RPM including deadhead, check timing feasibility, identify service risks, and decide whether to book, reject, or negotiate.',
    'Origin Joliet, IL to Hebron, KY. Loaded miles 310. Deadhead 42. Rate 925. Pickup 4:00 PM today. Delivery 11:00 PM today. Driver available 12:30 PM with 8.5 drive hours remaining.',
    '[{"criterion":"Calculation accuracy","weight":30,"description":"RPM and total-mile calculations include deadhead."},{"criterion":"Timing analysis","weight":30,"description":"Checks appointment timing against driver availability."},{"criterion":"Risk review","weight":20,"description":"Identifies trailer, HOS, traffic, and facility risks."},{"criterion":"Booking decision","weight":20,"description":"Decision is supported by calculations."}]'::jsonb,
    'calculation',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc7',
    '55555555-5555-4555-8555-555555555555',
    '55555555-5555-4555-8555-000000000002',
    'Late Pickup Scenario',
    'Manage late pickup risk on postal-style freight.',
    'Build a response plan covering driver instructions, stakeholder notification, route timing recovery, documentation, and follow-up after pickup.',
    'A driver assigned to a postal-style freight lane is delayed leaving the previous delivery. Pickup is scheduled for 6:00 PM, the driver ETA is now 6:40 PM, and the lane has an overnight delivery commitment.',
    '[{"criterion":"Service protection","weight":30,"description":"Prioritizes on-time performance and early escalation."},{"criterion":"Stakeholder communication","weight":25,"description":"Notifications are timely and factual."},{"criterion":"Route recovery","weight":25,"description":"Evaluates whether timing can still be recovered legally."},{"criterion":"Documentation","weight":20,"description":"Captures timestamps, cause, ETA, and pickup outcome."}]'::jsonb,
    'scenario',
    'intermediate',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc8',
    '55555555-5555-4555-8555-555555555555',
    '55555555-5555-4555-8555-000000000005',
    'Seal and Document Checklist',
    'Create a checklist for postal-style freight closeout and seal control.',
    'Create a dispatcher checklist covering pre-arrival, hook, seal check, paperwork review, departure update, and closeout.',
    'The driver must hook trailer PZ-4821, verify the seal, confirm trailer cleanliness, and submit paperwork after departure.',
    '[{"criterion":"Checklist completeness","weight":35,"description":"Covers trailer, seal, documents, timestamps, and closeout."},{"criterion":"Operational sequence","weight":25,"description":"Steps are ordered for real dispatch use."},{"criterion":"Seal control","weight":25,"description":"Seal number capture and mismatch escalation are clear."},{"criterion":"Documentation quality","weight":15,"description":"Requires legible paperwork and correct identifiers."}]'::jsonb,
    'checklist',
    'beginner',
    true
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-ccccccccccc9',
    '55555555-5555-4555-8555-555555555555',
    '55555555-5555-4555-8555-000000000007',
    'Route Timing Exercise',
    'Build a timing plan for a USPS-related freight training lane.',
    'Determine whether the lane is feasible, identify the tightest timing points, and write the update schedule for transit.',
    'Pickup Indianapolis, IN at 8:00 PM. Delivery Pittsburgh, PA by 5:30 AM. Loaded miles 360. Driver starts 35 miles from pickup at 6:30 PM. Average speed 58 mph. Fuel stop 25 minutes. Pre-trip and check-in buffer 35 minutes.',
    '[{"criterion":"Timing math","weight":35,"description":"Calculates deadhead, loaded drive time, stop, and buffer time accurately."},{"criterion":"Feasibility decision","weight":25,"description":"Decision is supported by the timeline."},{"criterion":"Risk identification","weight":20,"description":"Identifies traffic, weather, HOS, and facility timing risks."},{"criterion":"Update schedule","weight":20,"description":"Includes practical status update timing."}]'::jsonb,
    'calculation',
    'intermediate',
    true
  )
on conflict (id) do update
set title = excluded.title,
    description = excluded.description,
    instructions = excluded.instructions,
    scenario = excluded.scenario,
    rubric = excluded.rubric,
    type = excluded.type,
    difficulty = excluded.difficulty,
    published = excluded.published;
